version: '3.4'

services:
  ballastlane.taskmanagement.web:
    image: ${DOCKER_REGISTRY-}ballastlanetaskmanagementweb
    build:
      context: .
      dockerfile: Ballastlane.TaskManagement.Web/Dockerfile
    networks:
      - task-management-network
  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Pass@w0rd1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - task-management-network

networks:
  task-management-network:
    driver: bridge